import { pgTable, serial, integer } from "drizzle-orm/pg-core";

export const sunlight = pgTable("sunlight", {
  id: serial("id").primaryKey(),
  auckland: integer("auckland").notNull(),
  brisbane: integer("brisbane").notNull(),
  melbourne: integer("melbourne").notNull(),
  tokyo: integer("tokyo").notNull(),
  copenhagen: integer("copenhagen").notNull(),
  toronto: integer("toronto").notNull(),
  shanghai: integer("shanghai").notNull(),
  jakarta: integer("jakarta").notNull(),
  moscow: integer("moscow").notNull(),
  seoul: integer("seoul").notNull(),
  istanbul: integer("istanbul").notNull(),
  cairo: integer("cairo").notNull(),
  osaka: integer("osaka").notNull(),
  kyoto: integer("kyoto").notNull(),
  madrid: integer("madrid").notNull(),
  vancouver: integer("vancouver").notNull(),
  london: integer("london").notNull(),
  losangeles: integer("losangeles").notNull(),
  capetown: integer("capetown").notNull(),
  mexico: integer("mexico").notNull(),
  lima: integer("lima").notNull(),
  santiago: integer("santiago").notNull(),
  marrakesh: integer("marrakesh").notNull(),
  prague: integer("prague").notNull(),
  warsaw: integer("warsaw").notNull(),
  budapest: integer("budapest").notNull(),
  milan: integer("milan").notNull(),
  zurich: integer("zurich").notNull(),
});
